// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: packet.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PacketId  uint64                 `protobuf:"varint,1,opt,name=PacketId,proto3" json:"PacketId,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	// Types that are valid to be assigned to PacketData:
	//
	//	*Packet_Acknowledgement
	//	*Packet_Message
	//	*Packet_Sync
	PacketData    isPacket_PacketData `protobuf_oneof:"packet_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetPacketId() uint64 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *Packet) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Packet) GetPacketData() isPacket_PacketData {
	if x != nil {
		return x.PacketData
	}
	return nil
}

func (x *Packet) GetAcknowledgement() *Acknowledgement {
	if x != nil {
		if x, ok := x.PacketData.(*Packet_Acknowledgement); ok {
			return x.Acknowledgement
		}
	}
	return nil
}

func (x *Packet) GetMessage() *Message {
	if x != nil {
		if x, ok := x.PacketData.(*Packet_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Packet) GetSync() *Sync {
	if x != nil {
		if x, ok := x.PacketData.(*Packet_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

type isPacket_PacketData interface {
	isPacket_PacketData()
}

type Packet_Acknowledgement struct {
	Acknowledgement *Acknowledgement `protobuf:"bytes,3,opt,name=Acknowledgement,proto3,oneof"`
}

type Packet_Message struct {
	Message *Message `protobuf:"bytes,4,opt,name=Message,proto3,oneof"`
}

type Packet_Sync struct {
	Sync *Sync `protobuf:"bytes,5,opt,name=Sync,proto3,oneof"`
}

func (*Packet_Acknowledgement) isPacket_PacketData() {}

func (*Packet_Message) isPacket_PacketData() {}

func (*Packet_Sync) isPacket_PacketData() {}

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      uint64                 `protobuf:"varint,1,opt,name=PacketId,proto3" json:"PacketId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{1}
}

func (x *Acknowledgement) GetPacketId() uint64 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_packet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Sync struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsLocal           bool                   `protobuf:"varint,1,opt,name=IsLocal,proto3" json:"IsLocal,omitempty"`
	CommandFrameStart uint64                 `protobuf:"varint,2,opt,name=CommandFrameStart,proto3" json:"CommandFrameStart,omitempty"`
	CommandFrameEnd   uint64                 `protobuf:"varint,3,opt,name=CommandFrameEnd,proto3" json:"CommandFrameEnd,omitempty"`
	Deltas            []*Sync_FrameDelta     `protobuf:"bytes,4,rep,name=Deltas,proto3" json:"Deltas,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Sync) Reset() {
	*x = Sync{}
	mi := &file_packet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{3}
}

func (x *Sync) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *Sync) GetCommandFrameStart() uint64 {
	if x != nil {
		return x.CommandFrameStart
	}
	return 0
}

func (x *Sync) GetCommandFrameEnd() uint64 {
	if x != nil {
		return x.CommandFrameEnd
	}
	return 0
}

func (x *Sync) GetDeltas() []*Sync_FrameDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type Sync_FrameDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandFrame  uint64                 `protobuf:"varint,1,opt,name=CommandFrame,proto3" json:"CommandFrame,omitempty"`
	Changes       []*Sync_InstanceDelta  `protobuf:"bytes,2,rep,name=Changes,proto3" json:"Changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_FrameDelta) Reset() {
	*x = Sync_FrameDelta{}
	mi := &file_packet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_FrameDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_FrameDelta) ProtoMessage() {}

func (x *Sync_FrameDelta) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_FrameDelta.ProtoReflect.Descriptor instead.
func (*Sync_FrameDelta) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Sync_FrameDelta) GetCommandFrame() uint64 {
	if x != nil {
		return x.CommandFrame
	}
	return 0
}

func (x *Sync_FrameDelta) GetChanges() []*Sync_InstanceDelta {
	if x != nil {
		return x.Changes
	}
	return nil
}

type Sync_InstanceDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint64                 `protobuf:"varint,1,opt,name=InstanceId,proto3" json:"InstanceId,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=Created,proto3" json:"Created,omitempty"`
	Destroyed     bool                   `protobuf:"varint,3,opt,name=Destroyed,proto3" json:"Destroyed,omitempty"`
	Changes       *structpb.Struct       `protobuf:"bytes,4,opt,name=Changes,proto3" json:"Changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_InstanceDelta) Reset() {
	*x = Sync_InstanceDelta{}
	mi := &file_packet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_InstanceDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_InstanceDelta) ProtoMessage() {}

func (x *Sync_InstanceDelta) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_InstanceDelta.ProtoReflect.Descriptor instead.
func (*Sync_InstanceDelta) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Sync_InstanceDelta) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Sync_InstanceDelta) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *Sync_InstanceDelta) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

func (x *Sync_InstanceDelta) GetChanges() *structpb.Struct {
	if x != nil {
		return x.Changes
	}
	return nil
}

var File_packet_proto protoreflect.FileDescriptor

const file_packet_proto_rawDesc = "" +
	"\n" +
	"\fpacket.proto\x12\tingenuity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8c\x02\n" +
	"\x06Packet\x12\x1a\n" +
	"\bPacketId\x18\x01 \x01(\x04R\bPacketId\x128\n" +
	"\tTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x12F\n" +
	"\x0fAcknowledgement\x18\x03 \x01(\v2\x1a.ingenuity.AcknowledgementH\x00R\x0fAcknowledgement\x12.\n" +
	"\aMessage\x18\x04 \x01(\v2\x12.ingenuity.MessageH\x00R\aMessage\x12%\n" +
	"\x04Sync\x18\x05 \x01(\v2\x0f.ingenuity.SyncH\x00R\x04SyncB\r\n" +
	"\vpacket_data\"-\n" +
	"\x0fAcknowledgement\x12\x1a\n" +
	"\bPacketId\x18\x01 \x01(\x04R\bPacketId\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\"\xb4\x03\n" +
	"\x04Sync\x12\x18\n" +
	"\aIsLocal\x18\x01 \x01(\bR\aIsLocal\x12,\n" +
	"\x11CommandFrameStart\x18\x02 \x01(\x04R\x11CommandFrameStart\x12(\n" +
	"\x0fCommandFrameEnd\x18\x03 \x01(\x04R\x0fCommandFrameEnd\x122\n" +
	"\x06Deltas\x18\x04 \x03(\v2\x1a.ingenuity.Sync.FrameDeltaR\x06Deltas\x1ai\n" +
	"\n" +
	"FrameDelta\x12\"\n" +
	"\fCommandFrame\x18\x01 \x01(\x04R\fCommandFrame\x127\n" +
	"\aChanges\x18\x02 \x03(\v2\x1d.ingenuity.Sync.InstanceDeltaR\aChanges\x1a\x9a\x01\n" +
	"\rInstanceDelta\x12\x1e\n" +
	"\n" +
	"InstanceId\x18\x01 \x01(\x04R\n" +
	"InstanceId\x12\x18\n" +
	"\aCreated\x18\x02 \x01(\bR\aCreated\x12\x1c\n" +
	"\tDestroyed\x18\x03 \x01(\bR\tDestroyed\x121\n" +
	"\aChanges\x18\x04 \x01(\v2\x17.google.protobuf.StructR\aChangesB-Z+github.com/ouijan/ingenuity/pkg/net/packet;b\x06proto3"

var (
	file_packet_proto_rawDescOnce sync.Once
	file_packet_proto_rawDescData []byte
)

func file_packet_proto_rawDescGZIP() []byte {
	file_packet_proto_rawDescOnce.Do(func() {
		file_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_proto_rawDesc), len(file_packet_proto_rawDesc)))
	})
	return file_packet_proto_rawDescData
}

var file_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_packet_proto_goTypes = []any{
	(*Packet)(nil),                // 0: ingenuity.Packet
	(*Acknowledgement)(nil),       // 1: ingenuity.Acknowledgement
	(*Message)(nil),               // 2: ingenuity.Message
	(*Sync)(nil),                  // 3: ingenuity.Sync
	(*Sync_FrameDelta)(nil),       // 4: ingenuity.Sync.FrameDelta
	(*Sync_InstanceDelta)(nil),    // 5: ingenuity.Sync.InstanceDelta
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
}
var file_packet_proto_depIdxs = []int32{
	6, // 0: ingenuity.Packet.Timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: ingenuity.Packet.Acknowledgement:type_name -> ingenuity.Acknowledgement
	2, // 2: ingenuity.Packet.Message:type_name -> ingenuity.Message
	3, // 3: ingenuity.Packet.Sync:type_name -> ingenuity.Sync
	4, // 4: ingenuity.Sync.Deltas:type_name -> ingenuity.Sync.FrameDelta
	5, // 5: ingenuity.Sync.FrameDelta.Changes:type_name -> ingenuity.Sync.InstanceDelta
	7, // 6: ingenuity.Sync.InstanceDelta.Changes:type_name -> google.protobuf.Struct
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_packet_proto_init() }
func file_packet_proto_init() {
	if File_packet_proto != nil {
		return
	}
	file_packet_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Acknowledgement)(nil),
		(*Packet_Message)(nil),
		(*Packet_Sync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_proto_rawDesc), len(file_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_proto_goTypes,
		DependencyIndexes: file_packet_proto_depIdxs,
		MessageInfos:      file_packet_proto_msgTypes,
	}.Build()
	File_packet_proto = out.File
	file_packet_proto_goTypes = nil
	file_packet_proto_depIdxs = nil
}
