// Code generated by Ingenuity Tiled Codegen. DO NOT EDIT.
package types

type EditorClass struct {
	EditorType EditorEnum  `json:"EditorType"` // Default: "Editor1"
	ColorV     string      `json:"colorV"`     // Default: "#ff942193"
	FileV      string      `json:"fileV"`      // Default: "../ingenuity.json"
	FloatV     float64     `json:"floatV"`     // Default: "0"
	IntV       int         `json:"intV"`       // Default: "0"
	IsDead     bool        `json:"isDead"`     // Default: "false"
	Name       string      `json:"name"`       // Default: ""
	ObjectV    interface{} `json:"objectV"`    // Default: "0"
}

type EditorEnum string

const (
	Editor1 = "Editor1"
	Editor2 = "Editor2"
	Editor3 = "Editor3"
)
